title = "DokChess (arc42)"
baseURL = "https://www.dokchess.de/"

languageCode = "de-de"
defaultContentLanguage = "de"

# remove tags and categories pages
disableKinds = ["taxonomy"]

theme = "learn"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"

[Blackfriday]
# opens absolute links in a new window or tab
hrefTargetBlank = true

[markup.goldmark.renderer]
unsafe = true

[Languages]
[Languages.de]
title = "DokChess (arc42)"
weight = 1
languageName = "Español"

[Languages.en]
title = "DokChess (arc42)"
weight = 2
languageName = "English"


[[menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> Sobre el autor"
url = "/autor/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-file'></i> Licencia (CC BY-NC-SA)"
url = "/lizenz/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-star'></i> Créditos (Credits)"
url = "/abspann/"
weight = 12

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> Código fuente (GitHub)"
identifier = "ds"
url = "https://github.com/DokChess/"
weight = 13

[[menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Aviso legal"
url = "/impressum/"
weight = 14

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-user-circle'></i> Sobre el autor"
url = "/author/"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-file'></i> Licence (CC BY-NC-SA)"
url = "/licence/"
weight = 11


[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-star'></i> Credits"
url = "/credits/"
weight = 12

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Source code (GitHub)"
identifier = "ds"
url = "https://github.com/DokChess/"
weight = 13

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-info-circle'></i> Site Notice"
url = "/site_notice/"
weight = 14
